### ISSUE TITLE
nixpkgs.config and nixpkgs.overlays do not seem to work

### ISSUE THREAD

**Issue by throwup** [rycee/home-manager#226] opened 2018-03-08 23:14 UTC
Setting the `nixpkgs.config` and `nixpkgs.overlays` options in my home-manager configuration does not seem to do anything. This can probably most easily be replicated by setting:
`nixpkgs.config = { allowUnfree = true; }`
and trying to install a nonfree package via nix-env.
I am using the NixOS module to set my configuration.

**Comment by Infinisil** [comment] 2018-03-09 00:52
That's intended behaviour, these setting only apply to the `pkgs` set in the module evaluation. This is the same behaviour for nixos' `nixpkgs.*` options.

I guess this could be made clearer in the options description.

**Comment by rycee** [comment] 2018-03-10 10:18
Yeah, this is by design. In my configuration I have

```
nixpkgs.config = import dotfiles/nixpkgs-config.nix;
xdg.configFile."nixpkgs/config.nix".source = dotfiles/nixpkgs-config.nix;
```

to have the same configuration in both places.

**Comment by rycee** [comment] 2018-03-17 16:13
I'll close this issue now but I opened #230 to improve the option descriptions a bit. Please have a look and comment on the phrasing (which I didn't spend much time on).

**Closed by rycee** 2018-03-17 16:13 UTC

**Comment by taohansen** [comment] 2018-08-10 23:08
How does one allow nonfree packages in the scope of their `home.nx`?

**Comment by rycee** [comment] 2018-08-24 16:48
@taohansen Sorry for the delay. It should be possible with something like `nixpkgs.config.allowUnfree = true;` in your `home.nix`.

**Comment by asymmetric** [comment] 2020-05-22 20:11
> @taohansen Sorry for the delay. It should be possible with something like `nixpkgs.config.allowUnfree = true;` in your `home.nix`.

I just tried replacing the file in `~/.config/nixpkgs/config.nix` with the above in `home.nix`, but when switching HM complained about a non-free package - so it seems this is not working.
