### ISSUE TITLE
"/nix/store/...-news-info.sh: No such file or directory" with -2

### ISSUE THREAD

**Issue by norepicycle** [rycee/home-manager#327] opened 2018-07-31 03:35 UTC
```
$ home-manager -2 switch         
[4 built, 0.0 MiB DL]
Starting home manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating uninstallHomeManager
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
building '/nix/store/wxbp7g772i5pqg9sy6rafpqhbh2bnb7h-user-environment.drv'...
created 9 symlinks in user environment
Activating createHomeInfoDir
Activating linkGeneration
Cleaning up orphan links from /home/s
Creating profile generation 99
Creating home file links in /home/s
Activating onFilesChange
Activating reloadSystemD
User systemd daemon not running. Skipping reload.
/home/nor/.nix-profile/bin/home-manager: line 101: /nix/store/k3j2mhpxs4amwy7llyrz1m0pj26frb01-news-info.sh: No such file or directory
```

**Comment by rycee** [comment] 2018-07-31 11:55
Thanks for the report! I believe the issue is fixed in master now. Please give it a try and see how it goes 🙂

**Closed** 2018-07-31 11:54 UTC
