### ISSUE TITLE
Feature request: allow initExtra, profileExtra, etc to be paths

### ISSUE THREAD

**Issue by ghost** [rycee/home-manager#331] opened 2018-07-31 16:44 UTC
Right now I have to [work around](https://github.com/norepicycle/dotfiles/blob/master/home/programs.nix#L32) this with `builtins.readFile`.

**Comment by rycee** [comment] 2018-08-09 21:11
I'm inclined to say that this is by design and that the `builtins.readFile` is not a work around 🙂

I'll close this as a wontfix for now but if you feel really strongly about it then feel free to reopen.

**Closed by rycee** 2018-08-09 21:11 UTC
