### ISSUE TITLE
home-manager.useUserPackages does not appear to work with nix-darwin

### ISSUE THREAD

**Issue by BrianHicks** [rycee/home-manager#665] opened 2019-04-12 15:29 UTC
I am trying to set up home-manager with nix-darwin. It works OK so far! But I notice that `home-manager.useUserPackages = true;` does not seem to have any effect: my user packages in the home-manager config are not installed.

[I wrote up my experience here](https://github.com/BrianHicks/dotfiles.nix/blob/master/notes/home-manager-with-nix-darwin.org), with the intention of eventually contributing back to remove that `TODO: docs` line in the man page 😄. It's a bit rambly, so here's what I ended up with in a succinct way:

```nix
  users.users.brianhicks.name = "brianhicks";
  users.users.brianhicks.home = "/Users/brianhicks";
  home-manager.useUserPackages = true;
  home-manager.users.brianhicks = (import /Users/brianhicks/dotfiles.nix/macbook.nix);
```

**Comment by BrianHicks** [comment] 2019-04-12 15:30
oh, and here is the set of packages at the time of writing: https://github.com/BrianHicks/dotfiles.nix/blob/bb160dae50211c0e49a6c318a46dfb36cc3a9bcb/macbook.nix#L17-L29

**Comment by rycee** [comment] 2019-04-12 17:23
Thanks for the feedback! I know you need a relatively recent nix-darwin for it to work but unfortunately I can't help very much beyond that. Perhaps @kalbasit has some idea what the issue might be?

**Comment by BrianHicks** [comment] 2019-04-12 17:28
Mine's fairly recent; I installed it last week and updated everything before I did this. Sorry, I'm not sure how to find an exact version or commit hash yet… LMK if that would be helpful @kalbasit!

**Comment by kalbasit** [comment] 2019-04-13 05:04
How are you importing &lt;home-manager&gt;/nix-darwin? I see it in your notes, but I couldn't find it in your code.

Have a look at mine, perhaps you might find it helpful:
- home-manager is imported [here](https://github.com/kalbasit/shabka/blob/4d8dbe79c314debf8420ca4af16a2dbb28916196/modules/darwin/general/home-manager.nix#L15).
- users.users and home-manger.users is set [here](https://github.com/kalbasit/shabka/blob/4d8dbe79c314debf8420ca4af16a2dbb28916196/modules/darwin/general/users.nix#L22-L28).
- Each host set its own version of home-manager's config: [example](https://github.com/kalbasit/shabka/blob/master/hosts/athena/home.nix).
- Compare the version of home-manager/nix-darwin you're using with [mine](https://github.com/kalbasit/shabka/tree/master/external). Perhaps there's a regression somewhere. It has been quite some time since I have bumped the external dependencies in my configuration.

Out of all of the patches that I've submitted to make this work, #474 remains open. I'm not sure that it'll help you though.

**Comment by BrianHicks** [comment] 2019-04-13 10:44
🤔 Maybe I am just having trouble following the links between all those files, but it does not appear that you're setting `useUserPackages` in your darwin config? ([here in nix](https://github.com/kalbasit/shabka/blob/99d4294134cd5dcb12700af02ce9721522f61007/modules/nixos/general/home-manager.nix#L20), [not in the equivalent file in darwin](https://github.com/kalbasit/shabka/blob/99d4294134cd5dcb12700af02ce9721522f61007/modules/darwin/general/home-manager.nix).) How are you setting up your packages?

I mean, I could always import my HM config, extract the packages attribute, and use it separately… but I'd kind of rather not.

**Comment by BrianHicks** [comment] 2019-04-13 11:30
Did a little more digging, because it's very possible that I just have stuff set up incorrectly.

Here's [my full configuration.nix](https://github.com/BrianHicks/dotfiles.nix/blob/f261072a9e2dc039cc1e9c75b46c8c926da6ac22/macbook.nix) imported to the repo. This builds fine, but is still missing my user packages.

I moved `/etc/{zprofile,zshrc,zshenc}` out of the way when enabling ZSH through nix-darwin, so I would get the right variables… and set iterm to launch `/run/current-system/sw/bin/zsh -l` as my login shell.

I also [removed a manual sourcing in my `~/.zshrc`](https://github.com/BrianHicks/dotfiles.nix/commit/4814a37415f5bf3defe0fa26eee3e864d3fffc74) which I thought might be causing it.

Does that all see reasonable to y'all? What else should I try? What information might you look for as more experiences nixers that I am not while trying to figure this out?

**Comment by kalbasit** [comment] 2019-04-13 16:39
> :thinking: Maybe I am just having trouble following the links between all those files, but it does not appear that you're setting `useUserPackages` in your darwin config? ([here in nix](https://github.com/kalbasit/shabka/blob/99d4294134cd5dcb12700af02ce9721522f61007/modules/nixos/general/home-manager.nix#L20), [not in the equivalent file in darwin](https://github.com/kalbasit/shabka/blob/99d4294134cd5dcb12700af02ce9721522f61007/modules/darwin/general/home-manager.nix).) How are you setting up your packages?

:man_facepalming: I forgot that I ended up [not using it on my side](https://github.com/kalbasit/shabka/pull/172#issuecomment-466629929), I don't exactly remember why I was getting that error in my comment.

I see that you're setting up `users.users.<name>.{name,home}`, but you're not setting up [`users.knownUsers = ["<name>"]`](https://github.com/LnL7/nix-darwin/blob/51ecc4151f3dd5ae92c6eba5824ca77b72faa6df/modules/users/default.nix#L36-L44). IIRC, if the username is not in `users.knownUsers`, nix-darwin will not attempt to setup that user or it's packages, although [I might be wrong](https://github.com/LnL7/nix-darwin/blob/51ecc4151f3dd5ae92c6eba5824ca77b72faa6df/modules/users/default.nix#L164-L172).

**Comment by BrianHicks** [comment] 2019-04-13 18:38
Hmm, that doesn't appear to work. Further, it means that I need `users.users.me.uid` set for some reason? If I set `users.users.me.packages` those seem to get installed, but nothing from home-manager ever shows up. Is it possible that things are not getting symlinked correctly, or not ending in the environment in the right place? 

Here's what I end up with in my `$PATH`…

```
/usr/local/bin
/Users/brianhicks/.nix-profile/bin
/run/current-system/sw/bin
/nix/var/nix/profiles/default/bin
/usr/local/bin
/usr/bin
/usr/sbin
/bin
/sbin
```

of those, none include things I specify in `packages` (like `jq` for me) or `imports` (like importing my `fzf` config and including the binary.)

Any other ideas? I'm about to give up here.

**Comment by BrianHicks** [comment] 2019-04-30 15:55
I'm really curious to get this working. Any ideas what could be interfering with it? Maybe some environment variable, or nix setup? I'm happy to give any information that would be helpful!

**Comment by rvolosatovs** [comment] 2019-05-04 11:35
@BrianHicks can you verify if https://github.com/rycee/home-manager/pull/702 fixes the issue?

**Comment by BrianHicks** [comment] 2019-05-04 20:02
it appears to have worked for me, yes! Hooray!

**Comment by rycee** [comment] 2019-08-15 12:36
From what I can tell it is safe to close this issue. If I'm wrong, please reopen.

**Closed by rycee** 2019-08-15 12:36 UTC
