### ISSUE TITLE
Deactivating tests per overlay ignored

### ISSUE THREAD

**Issue by 573** [rycee/home-manager#1272] opened 2020-05-25 12:22 UTC
I have in my home.nix:
```
  nixpkgs.overlays = [
    (self: super: {
      # https://discourse.nixos.org/t/nix-haskell-development-2020/6170/2
      haskellPackages = super.haskellPackages.override {
        overrides = hself: hsuper: rec {
          mkDerivation = args: hsuper.mkDerivation (args // {
            doCheck = false;
            doHaddock = false;
            enableLibraryProfiling = false;
            enableExecutableProfiling = false;
            jailbreak = true;
          });
        };
      };
    })
  ];

  home.packages = with pkgs; [
    (let neuronRev = "e5a807d43bdb1e1c59c03119f3520a46db4a5660";
     neuronSrc = builtins.fetchTarball "https://github.com/srid/neuron/archive/${neuronRev}.tar.gz";
     in import neuronSrc)
  ];
```

Still quickcheck is being executed.

**Comment by Kloenk** [comment] 2020-05-25 12:43
I'm not sure if I understand everything, because I'm not familiar with the Haskell packages in nixpkgs. But if I see it correctly neuron does not honor the options set to nixpkgs locally. So I guess it is expected behavior or an error in neuron/nixpkgs.

**Comment by Kloenk** [comment] 2020-05-28 11:06
I think this is sufficiently handled in https://github.com/srid/neuron/issues/207

Could you close it, and reopen a new one if neuron creates an interface where we could hook into?

**Closed** 2020-05-28 11:30 UTC
